# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55dc45cb9c2b4173024e3f4c1ad486af0c06b43ac0f016bc46a7792048b2530787baa59ee2b66dc60a09549a29d0cb3da97c3d2455ea84d9e55e9d7e5db3b86e

test:
  secret_key_base: f31d51b234f7066dc193eefe9dc3bfc8cbb734b21946737482150a7c79962d6b1020e4bd3c28ff20297c9d0e0809f72f9ba6c38a8eab9c802d182667a1fd61ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
